import 'dart:convert';
import 'dart:io';
import 'dart:math';

import 'package:carousel_slider/carousel_slider.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:covidia/api/authentication_api.dart';
import 'package:covidia/api/firebase_api.dart';
import 'package:covidia/api/tflite_api.dart';
import 'package:covidia/models/models.dart';
import 'package:covidia/presentation/widgets/widgets.dart';
import 'package:covidia/providers/preview_provider.dart';
import 'package:covidia/providers/providers.dart';
import 'package:covidia/providers/sign_up_provider.dart';
import 'package:covidia/shared/shared.dart';
import 'package:covidia/util/util.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_svg/svg.dart';
import 'package:fluttertoast/fluttertoast.dart';
import 'package:image_cropper/image_cropper.dart';
import 'package:image_picker/image_picker.dart';
import 'package:path/path.dart' as path;
import 'package:provider/provider.dart';
import 'package:tflite/tflite.dart';

part 'detail_page.dart';
part 'home_page.dart';
part 'main_page.dart';
part 'preview_page.dart';
part 'setting_page.dart';
part 'sign_in_page.dart';
part 'authentication_wrapper.dart';
part 'reset_password_page.dart';
part 'reset_email_sent.dart';
part 'sign_up_page.dart';
